# Generated by Django 6.0.3 on 2026-05-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsgupadmin', '0002_certificate_quiz_question_quizattempt_quizresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistermodel',
            name='password',
        ),
    ]
