# Generated by Django 6.0.3 on 2026-05-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsgupadmin', '0003_remove_userregistermodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistermodel',
            name='is_active_student',
            field=models.BooleanField(default=True),
        ),
    ]
