# Generated by Django 6.0.3 on 2026-05-25 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsgupadmin', '0004_userregistermodel_is_active_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsgupadmin.userregistermodel')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('file', 'File')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('options', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='bsgupadmin.dynamicform')),
            ],
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsgupadmin.dynamicform')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsgupadmin.userregistermodel')),
            ],
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='form_uploads/')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsgupadmin.dynamicfield')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='bsgupadmin.formresponse')),
            ],
        ),
    ]
