# Generated by Django 6.0.3 on 2026-05-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsgupadmin', '0005_dynamicform_dynamicfield_formresponse_formanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userregistermodel',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userregistermodel',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
